services:
  grafana:
    user: root
    container_name: 'elis-mappa-panel'

    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-9.0.1}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/elis-mappa-panel
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/elis-mappa-panel

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.elis-mappa-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: elis-mappa-panel
      DOCKER_TLS_VERIFY: "1"
      DOCKER_BUILDKIT: 0
      COMPOSE_DOCKER_CLI_BUILD: 0
